### ISSUE TITLE
static bucket without Cloud Internet Services and missing error.html

### ISSUE THREAD

**Issue by miksch27** [IBM-Cloud/serverless-guestbook#14]
Well, hello :-)  
I tried your guestbook. Somehow. okay. 
Well, I don't want to use CIS(intenet services) for my demo. Because the 'static web service' of your bucket demo points  to this further, expensive service.

Do you know an alternated, quick, non-productive way to redirect a private owned subdomain name? 
My provider added .../defaultsite somehow.    bit.ly doesn't work, too.

Furthermore, I added an error.html in my bucket. This file helped me to understand that somehow my redirections worked partly...

Thx.

**Comment by l2fprod** [comment]
CIS is an optional step.

If you own a domain, you can serve the app directly from the COS bucket and use a CNAME with the COS bucket to use your own domain https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-routing-rules-cos. You would keep the IBM provided domain for Cloud Functions.
